### ISSUE TITLE
 Unable to load DLL 'opencvforunity'

### ISSUE THREAD

**Issue by khanxc** [EnoxSoftware/HoloLensWithOpenCVForUnityExample#4]
I am getting this error in the log, I followed the setup instructions. So where am I going wrong?

`Exception thrown: 'System.DllNotFoundException' in Assembly-CSharp.dll
DllNotFoundException: Unable to load DLL 'opencvforunity': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at OpenCVForUnity.Mat.core_Mat_n_1Mat__III(Int32 rows, Int32 cols, Int32 type)
   at HoloLensWithOpenCVForUnityExample.WebCamTextureToMatHelper.<init>d__23.MoveNext()
   at UnityEngine.SetupCoroutine.InvokeMoveNext(IEnumerator enumerator, IntPtr returnValueAddress)
   at UnityEngine.SetupCoroutine.$Invoke1(Int64 instance, Int64* args)
   at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64* args, IntPtr method) 
(Filename: <Unknown> Line: 0)`

**Comment by khanxc** [comment]
Closing this. Read the Q&A in Enox website. Which mentioned about how to integrate OpenCV for unity in UWP and that solved my prob. Link to Q&A [Enox Q&A](https://enoxsoftware.com/opencvforunity/documentation/q-a/)
